import './hero-scroll.js';
import { initTrustHeading } from './trust-heading.js';
import { initHeroOffers } from './hero-offers.js';
import { initPageLoading } from './page-loading.js';
import { initNavMenu } from './nav-menu.js';
import { initParallax } from './parallax.js';
import { initFooterSvg } from './footer-svg.js';
import { initContactModal } from './contact-modal.js';
import { initCaseModal } from './case-modal.js';
import { initAccordion } from './accordion.js';
import { initDrawSvg } from './draw-svg.js';
import { initRotateY } from './rotate-y.js';
import { initHeroNavLinks } from './hero-nav-links.js';
import { initPageTransition } from './page-transition.js';

document.addEventListener('DOMContentLoaded', () => {
  initHeroNavLinks();
  initPageLoading();
  initTrustHeading();
  initHeroOffers();
  initNavMenu();
  initParallax();
  initFooterSvg();
  initContactModal();
  initCaseModal();
  initAccordion();
  initDrawSvg();
  initRotateY();
  initPageTransition();
});
